name: Trigger auto deployment for eshop-product-aa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/eshop-product-aa-AutoDeployTrigger-08906136-3b8b-4437-808d-5a65c8aa48ca.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.ESHOPPRODUCTAA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/ProductMicroservices/ProductAPI
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: eshopacraa.azurecr.io
          registryUsername: ${{ secrets.ESHOPPRODUCTAA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ESHOPPRODUCTAA_REGISTRY_PASSWORD }}
          containerAppName: eshop-product-aa
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: eshopacraa.azurecr.io/eshop-product-aa:${{ github.sha }}
          
            

     

